routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user, login_required

from models.connection import db
from models.model import User

app = Blueprint('auth', __name__)

@app.route('/')
def login():
    if current_user.is_authenticated:
        flash('User already authenticated.')
        return redirect(url_for('default.request_vm'))
    else:
        return render_template('/auth/login.html')

@app.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    
    stmt = db.select(User).filter_by(email=email)
    user = db.session.execute(stmt).scalar_one_or_none()

    if user:
        if user.check_password(password):
            login_user(user)
            flash('Logged in successfully.')
            return redirect(url_for('default.request_vm'))
        else:
            flash('Invalid password. Please try again.')
            return redirect(url_for('auth.login'))
    else:
        flash('Invalid account. Please try again.')
        return redirect(url_for('auth.login'))


@app.route('/logout')
@login_required
def logout():
    username = current_user.username
    logout_user()
    return render_template('/auth/logout.html', name=username)

routes/default.py
from flask import Blueprint, redirect, url_for, render_template, request, jsonify, flash
from flask_login import current_user, login_required

from models.connection import db
from models.model import User, VMRequest, VMConfig
from proxmoxer import ProxmoxAPI
from models.config import Config

app = Blueprint('default', __name__)

@app.route('/')
def home():
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))

    if current_user.role == 'admin':
        return redirect(url_for('admin.admin_dashboard'))
    elif current_user.role == 'user':
        return redirect(url_for('default.request_vm'))

    return redirect(url_for('auth.login'))

@app.route('/request-vm', methods=['GET', 'POST'])
@login_required
def request_vm():
    return render_template('vm/request-new-vm.html')

@app.route('/requestNewVM', methods=['GET', 'POST'])
@login_required
def request_new():
    if request.method == 'POST':
        hostname = request.form.get('hostname')
        config_id = request.form.get('config_id')
        config = VMConfig.query.get(config_id)
        
        if config:
            new_request = VMRequest(
                user_id=current_user.id,
                config_name=config.name,
                hostname=hostname,
                status='pending'
            )

            db.session.add(new_request)
            db.session.commit()
            flash(f"Richiesta per {hostname} inviata con successo!")
            return redirect(url_for('default.request_vm'))

    query = VMConfig.query.all()
    return render_template('vm/vm-request.html',val=query)

@app.route('/get-vm-ip/<int:vmid>', methods=['GET'])
@login_required
def get_vm_ip(vmid):
    node = Config.PROXMOX_NODE
    try:
        proxmox = ProxmoxAPI(
            Config.PROXMOX_HOST, 
            user=Config.PROXMOX_USER, 
            password=Config.PROXMOX_PASSWORD, 
            verify_ssl=Config.PROXMOX_VERIFY_SSL
        )
        
        status = proxmox.nodes(node).qemu(vmid).status.current.get()
        if status.get('status') != 'running':
            return jsonify({"ip": "VM Spenta", "details": "Avvia la VM su Proxmox"}), 202

        net = proxmox.nodes(node).qemu(vmid).agent('network-get-interfaces').get()
        for iface in net.get('result', []):
            for addr in iface.get('ip-addresses', []):
                if addr.get('ip-address-type') == 'ipv4' and not addr['ip-address'].startswith('127'):
                    new_ip = addr['ip-address']
                    vm_req = VMRequest.query.filter_by(vm_id=vmid).first()
                    if vm_req:
                        vm_req.ip_address = new_ip
                        db.session.commit()
                        
                    return jsonify({"ip": new_ip}), 200
        
        return jsonify({"ip": "In attesa...", "details": "Il DHCP non ha ancora assegnato l'IP"}), 202

    except Exception as e:
        return jsonify({"ip": "Agent non pronto", "details": str(e)}), 202

@app.route('/userForm')
def user_form_display():
    return render_template('userForm.html')

@app.route('/form', methods=['POST'])
def form_process():
    return "form process"

@app.route('/adduser', methods=['POST'])
def add_user():
    username = request.json.get('username')
    email = request.json.get('email')
    password = request.json.get('password')

    user = User(username=username, email=email)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()
    
    return jsonify({"message": "Utente creato con successo"}), 200

templates/base.html
<html>
<head>
  <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{url_for('default.home')}}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('default.request_vm')}}">VM Richieste</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('default.request_new')}}">Richiedi VM</a>
          </li>
          {% if not current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
          </li>
          {%endif%}
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
          </li>
          {%endif%}
        </ul>
      </div>
    </div>
  </nav>
  {% with messages = get_flashed_messages()%}
  {% if messages%}
  <div class="alert alert-info" role="alert">
    {% for message in messages%}
    <p>{{message}}</p>
    {%endfor%}
  </div>
    {%endif%}
    {%endwith%}
  {% block content %}{% endblock %}
</body>
</html>

templates/index.html
<html>
<body>
  {% extends "base.html" %}

  {% block title %}Home Page{% endblock %}

  {% block content %}
    <h1>Welcome {{ name }} to the Home Page!</h1>
  {% endblock %}
</body>
</html>

templates/userForm.html
<body>
  {% extends "base.html" %}
  {% block title %}Form Page{% endblock %}

  {% block content %}
  <div class="container w-25">
    <h1>Aggiungi Utente</h1>
    <form id="userForm">
      <label for="username">Username:</label><br>
      <input type="text" class="form-control" id="username" name="username" required><br>

      <label for="email">Email:</label><br>
      <input type="email" class="form-control" id="email" name="email" required><br>

      <label for="password">Password:</label><br>
      <input type="password" class="form-control" id="password" name="password" required><br>

      <button type="submit" class="btn btn-outline-dark">Invia</button>
    </form>
  </div>

  <div id="response"></div>

  <script>
    document.getElementById('userForm').addEventListener('submit', function (e) {
      e.preventDefault();
      const data = {
          username: document.getElementById('username').value,
          email: document.getElementById('email').value,
          password: document.getElementById('password').value,
      };

      fetch('/adduser', {
          method: 'POST',
          headers: {
              'Content-Type': 'application/json'
          },
          body: JSON.stringify(data)
      })
      .then(response => response.json())
      .then(result => {
        document.getElementById('response').innerText = result.message;
      })
      .catch(error => {
        document.getElementById('response').innerText = 'Errore durante l\'invio';
        console.error('Errore:', error);
      });
    });
  </script>

  {% endblock %}
</body>
</html>